### ISSUE TITLE
Is C++17 support required?

### ISSUE THREAD

**Issue by DymOK93** [DymOK93/KTL#125]
Maybe it's worth switching to use of C++20 only?

**Comment by GeorgyFirsov** [comment]
Even C++17 is used not in all organizations now, e.g. kernel-mode drivers in my company are written using C++14.

Furthermore, C++20 is currently not widely spread even for user-mode applications. So it makes sense to keep library able to support older standards for a few years, but I suppose, that conditional compilation can be applied to make some optimizations for the last language version.

As for me, such libraries as KTL, should support (maybe partially) at least 3 last language versions, but not to focus on the last one.

**Comment by DymOK93** [comment]
Okay, I agree.  Moreover, kernel development is a quiet conservative area from the point of view of a programming language features

Now compiling of KTL requires C++17, (low-level runtime library part as well). I was thinking about supporting C++14... But haven't implemented yet 

Let's use C++17 for now with compatibility to build with C++20 (for coroutines, etc.)

P. S. Kernel-mode drivers in my company are written using C++17 or pure C :)
