### ISSUE TITLE
Rename thread.h and other *.h headers to *.hpp before the first major release

### ISSUE THREAD

**Issue by GeorgyFirsov** [DymOK93/KTL#136]
For consistency with the rest of headers

**Comment by DymOK93** [comment]
Oh... It's a long story.
Initially, the use of .h and .hpp headers had a certain idea: I meant that .h required linking to the corresponding .lib, but .hpp didn't. For example: 
* <thread.h> requires linking to the both `ktl::basic_runtime` and `ktl::cpp_runtime`
* <chrono.hpp> requires linking to the only `ktl::basic_runtime`
* <algorithm_impl.hpp> from the `runtime/` subdirectory doesn't required linking to anything

But now I see this approach is awkward:
* It is not clear which header extension to choose when using the library as an STL replacement for kernel mode. To choose between .h and .hpp, it's to have to read the documentation or try at random. You are no longer the first person to ask me about this :)
* When adding new functionality to the .hpp header that can be implemented in .cpp, it's to have to break library own conventions or rename the header to .h, breaking the library API 

I think the issue should be expanded to "rename __all__ headers to .hpp"

**Comment by GeorgyFirsov** [comment]
> I think the issue should be expanded to "rename all headers to .hpp"

I agree, but such refactoring must be completed __before__ the first major release, because changing an interface (headers are a part of it) is highly undesirable after that.

**Comment by DymOK93** [comment]
Closed by #149
